#!/usr/bin/env node
// Generate tool-specific folders from the canonical source.
//
//   agents/*.md            (canonical, hand-edited)
//   skills/*/SKILL.md      (canonical, hand-edited)
//   domains/*/loop.md      (canonical, hand-edited)
//        |
//        v   node tools/generate.mjs
//   .cursor/agents/*  .cursor/skills/*     (Cursor)
//   .claude/agents/*  .claude/skills/*     (Claude Code)
//   domains/*/AGENTS.md                    (org-chart index)
//   CLAUDE.md                              (Claude Code entry point)
//
// Zero dependencies (Node >= 18 stdlib). Idempotent: running twice makes no diff.
import {
  readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync, cpSync, existsSync,
} from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

// SRC  = where the canonical source lives (parent of this tools/ dir).
// OUT  = where generated tool folders (.cursor/.claude/CLAUDE.md) are written.
//        Same as SRC in this template repo. When the swarm is vendored into a
//        consumer repo under `.agentsmith/`, OUT is that repo's root so the
//        tools find their folders at the top level. Override with AGENTSMITH_OUT.
const SRC = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = process.env.AGENTSMITH_OUT
  ? process.env.AGENTSMITH_OUT
  : basename(SRC) === '.agentsmith' ? dirname(SRC) : SRC;
const p = (...a) => join(SRC, ...a);       // read canonical source + write docs
const o = (...a) => join(OUT, ...a);       // write generated tool folders

// ---------- tiny frontmatter parser (scalars only) ----------
function parse(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return { fm: {}, body: text.trim() };
  const fm = {};
  for (const line of m[1].split('\n')) {
    const mm = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/);
    if (mm) fm[mm[1]] = mm[2].trim();
  }
  return { fm, body: m[2].trim() };
}
const list = (v) => (v ? v.split(',').map((s) => s.trim()).filter(Boolean) : []);

// ---------- load canonical agents ----------
const agents = readdirSync(p('agents'))
  .filter((f) => f.endsWith('.md'))
  .map((f) => {
    const { fm, body } = parse(readFileSync(p('agents', f), 'utf8'));
    return { file: f, name: fm.name || f.replace(/\.md$/, ''), fm, body };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

// Append a generated "## Skills" section so both tools show the role's skills.
function withSkills(body, fm) {
  const skills = list(fm.skills);
  if (!skills.length) return body;
  const sec = '## Skills\n\n' + skills.map((s) => `- \`${s}\``).join('\n');
  return `${body}\n\n${sec}`;
}

function frontmatter(pairs) {
  const lines = pairs.filter(([, v]) => v != null && v !== '').map(([k, v]) => `${k}: ${v}`);
  return `---\n${lines.join('\n')}\n---\n`;
}

// ---------- reset generated dirs ----------
for (const d of ['.cursor/agents', '.claude/agents', '.cursor/skills', '.claude/skills']) {
  rmSync(o(d), { recursive: true, force: true });
  mkdirSync(o(d), { recursive: true });
}

// ---------- emit agents ----------
for (const a of agents) {
  const body = withSkills(a.body, a.fm);

  // Cursor: name + description only.
  const cursor = frontmatter([['name', a.name], ['description', a.fm.description]]) + '\n' + body + '\n';
  writeFileSync(o('.cursor/agents', a.file), cursor, 'utf8');

  // Claude Code: name, description, tools, model (documented fields).
  const claude = frontmatter([
    ['name', a.name],
    ['description', a.fm.description],
    ['tools', a.fm.tools],
    ['model', a.fm.model],
  ]) + '\n' + body + '\n';
  writeFileSync(o('.claude/agents', a.file), claude, 'utf8');
}

// ---------- copy skills verbatim ----------
cpSync(p('skills'), o('.cursor/skills'), { recursive: true });
cpSync(p('skills'), o('.claude/skills'), { recursive: true });

// ---------- regenerate domain AGENTS.md indexes ----------
const domains = readdirSync(p('domains')).filter((d) => existsSync(p('domains', d, 'loop.md')));
for (const domain of domains) {
  const { fm, body } = parse(readFileSync(p('domains', domain, 'loop.md'), 'utf8'));
  const roles = agents.filter((a) => a.fm.domain === domain);
  const roleLines = roles.map((a) => `- \`${a.name}\`: ${a.fm.description}`).join('\n');
  const skills = list(fm.skills);
  const skillLine = skills.length ? `\n### Key skills commonly used\n\n${skills.map((s) => `\`${s}\``).join(', ')}\n` : '';
  const out =
`<!-- GENERATED by tools/generate.mjs from domains/${domain}/loop.md + agents/*.md. Do not edit by hand. -->

## ${fm.title || domain}

${fm.summary || ''}

### Roles (agents)

${roleLines}

${body}
${skillLine}`;
  writeFileSync(p('domains', domain, 'AGENTS.md'), out, 'utf8');
}

// ---------- generate CLAUDE.md ----------
const byDomain = {};
for (const a of agents) (byDomain[a.fm.domain] ||= []).push(a);
const domainOrder = ['web_app', 'backend_heavy', 'embedded', 'cross_cutting'];
const domainNames = Object.keys(byDomain).sort(
  (a, b) => (domainOrder.indexOf(a) + 1 || 99) - (domainOrder.indexOf(b) + 1 || 99),
);
const rosterBlocks = domainNames.map((d) => {
  const rows = byDomain[d].map((a) => `- \`${a.name}\` — ${a.fm.description}`).join('\n');
  return `### ${d}\n\n${rows}`;
}).join('\n\n');

const claudeMd = `<!-- GENERATED by tools/generate.mjs. Edit templates/canonical sources, not this file. -->

# AgentSmith Swarm

This project carries an AgentSmith agent swarm — a set of specialist subagents
plus reusable skills — under \`.claude/agents/\` and \`.claude/skills/\`.

## How to run a team

1. **Personalize first (once per project):** run the \`project-intake\` agent. It
   interviews you, writes \`.agentsmith/profile.md\`, and prunes/tunes the swarm to
   your stack.
2. **For any non-trivial change:** invoke the \`orchestrator\` agent. It picks the
   domain, runs the collaboration loop (PM → design → engineering → architecture
   review → QA → devops), and dispatches to the specialists below.
3. **For a targeted review:** invoke a single specialist (e.g. \`security-architect\`,
   \`web-system-architect\`).

## Available agents

${rosterBlocks}

## Skills

Reusable playbooks live in \`.claude/skills/\`: ${
  readdirSync(p('skills')).filter((s) => existsSync(p('skills', s, 'SKILL.md'))).map((s) => `\`${s}\``).join(', ')
}.

## Editing the swarm

Do **not** edit \`.claude/\` or \`.cursor/\` by hand — they are generated. Edit the
canonical source in \`agents/*.md\`, \`skills/*/SKILL.md\`, and \`domains/*/loop.md\`,
then run \`node tools/generate.mjs\`.
`;
writeFileSync(o('CLAUDE.md'), claudeMd, 'utf8');

console.log(`Generated ${agents.length} agents -> .cursor/ + .claude/, ${domains.length} domain indexes, CLAUDE.md (out: ${OUT})`);
